language: cpp

compiler:
  - clang

# add cmake
addons:
  apt:
    packages:
      - cmake

before_install:
  # Make permissions granted
  - sudo chmod +x /usr/bin/make
  - sudo chown -R `whoami` /usr/local

  # Ubuntu Toolchain
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
  - sudo apt-get update

  # clang ppa
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq

install:
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script:
  - $CXX --version
  - git clone https://github.com/redis/hiredis --depth 1
  - cd hiredis
  - make && make install
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
